"""
Response services for sending notifications (DingTalk, etc.)
"""
import logging
import time
import hmac
import hashlib
import base64
import urllib.parse
import requests
from django.conf import settings

logger = logging.getLogger(__name__)


class DingTalkService:
    """
    Service for sending DingTalk notifications
    """

    def __init__(self):
        self.webhook_url = settings.DINGDING_BOT_WEBHOOK
        self.secret = settings.DINGDING_SECRET

    def send_markdown_message(self, title, content):
        """
        Send markdown message to DingTalk
        """
        if not self.webhook_url:
            logger.warning("DingTalk webhook URL not configured")
            return False

        try:
            # Generate signature if secret is provided
            url = self.webhook_url
            if self.secret:
                timestamp = str(round(time.time() * 1000))
                sign = self._generate_signature(timestamp)
                url = f"{self.webhook_url}&timestamp={timestamp}&sign={sign}"

            # Build message payload
            payload = {
                "msgtype": "markdown",
                "markdown": {
                    "title": title,
                    "text": content
                }
            }

            # Send request
            response = requests.post(url, json=payload, timeout=10)
            response.raise_for_status()

            result = response.json()
            if result.get('errcode') == 0:
                logger.info("DingTalk message sent successfully")
                return True
            else:
                logger.error(f"DingTalk API error: {result}")
                return False

        except Exception as e:
            logger.error(f"Error sending DingTalk message: {e}", exc_info=True)
            return False

    def _generate_signature(self, timestamp):
        """
        Generate signature for DingTalk webhook
        """
        secret_enc = self.secret.encode('utf-8')
        string_to_sign = f'{timestamp}\n{self.secret}'
        string_to_sign_enc = string_to_sign.encode('utf-8')

        hmac_code = hmac.new(secret_enc, string_to_sign_enc, digestmod=hashlib.sha256).digest()
        sign = urllib.parse.quote_plus(base64.b64encode(hmac_code))

        return sign


class NotificationService:
    """
    Unified notification service
    """

    def __init__(self):
        self.dingtalk = DingTalkService()

    def notify_review_completed(self, project_name, merge_request_iid, review_content):
        """
        Notify when code review is completed
        """
        title = f"代码审查完成 - {project_name}"
        content = f"""
## {title}

**MR #{merge_request_iid}**

{review_content}

---
*Generated by Code Review GPT*
        """

        return self.dingtalk.send_markdown_message(title, content)
