# Generated by Django 4.1.13 on 2025-11-05 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_url', models.URLField(default='https://gitlab.com', max_length=500)),
                ('private_token', models.CharField(blank=True, max_length=500)),
                ('max_files', models.IntegerField(default=50)),
                ('context_lines', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gitlab_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('claude', 'Anthropic Claude'), ('gemini', 'Google Gemini')], default='openai', max_length=50)),
                ('model', models.CharField(default='gpt-4', max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_base', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('dingtalk', '钉钉通知'), ('gitlab', 'GitLab评论'), ('email', '邮件通知'), ('slack', 'Slack通知'), ('wechat', '微信通知')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('config_data', models.TextField(blank=True, default='{}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_configs',
                'ordering': ['-created_at'],
                'unique_together': {('notification_type',)},
            },
        ),
    ]
