# Generated by Django 4.1.13 on 2025-11-06 22:44

from django.db import migrations, models
import django.utils.timezone
import json


def migrate_notification_configs(apps, schema_editor):
    NotificationConfig = apps.get_model('llm', 'NotificationConfig')
    NotificationChannel = apps.get_model('llm', 'NotificationChannel')

    type_labels = {
        'dingtalk': '钉钉',
        'gitlab': 'GitLab',
        'email': '邮件',
        'slack': 'Slack',
        'feishu': '飞书',
        'wechat': '企业微信',
    }

    existing_names = set()

    for config in NotificationConfig.objects.all():
        label = type_labels.get(config.notification_type, config.notification_type)
        base_name = f"默认{label}通道"
        name = base_name
        index = 1
        while name in existing_names:
            index += 1
            name = f"{base_name}{index}"

        existing_names.add(name)

        config_data = config.config_data or '{}'
        try:
            json.loads(config_data)
        except (TypeError, json.JSONDecodeError):
            config_data = '{}'

        NotificationChannel.objects.create(
            name=name,
            notification_type=config.notification_type,
            description='迁移自旧版通知配置',
            is_active=config.is_active and config.enabled,
            is_default=config.enabled and config.is_active,
            config_data=config_data,
        )


def reverse_notification_configs(apps, schema_editor):
    NotificationChannel = apps.get_model('llm', 'NotificationChannel')
    NotificationChannel.objects.filter(description='迁移自旧版通知配置').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('dingtalk', '钉钉通知'), ('gitlab', 'GitLab评论'), ('email', '邮件通知'), ('slack', 'Slack通知'), ('feishu', '飞书通知'), ('wechat', '企业微信通知')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='用于新项目的默认通道')),
                ('config_data', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_channels',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='notificationconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='notification_type',
            field=models.CharField(choices=[('dingtalk', '钉钉通知'), ('gitlab', 'GitLab评论'), ('email', '邮件通知'), ('slack', 'Slack通知'), ('feishu', '飞书通知'), ('wechat', '企业微信通知')], max_length=50),
        ),
        migrations.RunPython(migrate_notification_configs, reverse_notification_configs),
    ]
