# Generated by Django 4.1.13 on 2025-11-08 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_notificationchannel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='事件规则的名称，用于展示和选择', max_length=255)),
                ('event_type', models.CharField(help_text='GitLab事件类型，如：Merge Request Hook, Push Hook', max_length=100)),
                ('description', models.TextField(blank=True, help_text='事件规则的详细描述')),
                ('match_rules', models.TextField(help_text='JSON格式的事件匹配规则')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_event_rules',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookeventrule',
            index=models.Index(fields=['event_type'], name='webhook_eve_event_t_956323_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventrule',
            index=models.Index(fields=['is_active'], name='webhook_eve_is_acti_1f856f_idx'),
        ),
    ]
