# Generated by Django 4.1.13 on 2025-11-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_webhookeventrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabconfig',
            name='context_lines',
        ),
    ]
