# Generated by Django 4.1.13 on 2025-11-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_remove_gitlabconfig_context_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabconfig',
            name='max_files',
        ),
    ]
