# Generated by Django 4.1.13 on 2025-11-17 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_remove_gitlabconfig_max_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeCliConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anthropic_base_url', models.URLField(blank=True, help_text='ANTHROPIC_BASE_URL - Claude API 基础地址', max_length=500, null=True)),
                ('anthropic_auth_token', models.CharField(blank=True, help_text='ANTHROPIC_AUTH_TOKEN - Claude 认证令牌', max_length=500)),
                ('cli_path', models.CharField(default='claude', help_text='Claude CLI 可执行文件路径', max_length=500)),
                ('timeout', models.IntegerField(default=300, help_text='Claude CLI 执行超时时间（秒）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claude_cli_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
