# Generated by Django 4.1.13 on 2025-11-05 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequestReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_index=True)),
                ('project_name', models.CharField(max_length=255)),
                ('merge_request_iid', models.IntegerField(db_index=True)),
                ('merge_request_title', models.CharField(max_length=500)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('review_content', models.TextField()),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('files_reviewed', models.TextField(blank=True, default='[]')),
                ('total_files', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_sent', models.BooleanField(default=False)),
                ('response_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'merge_request_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(db_index=True, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_path', models.CharField(max_length=500)),
                ('project_url', models.URLField(max_length=500)),
                ('namespace', models.CharField(max_length=255)),
                ('review_enabled', models.BooleanField(db_index=True, default=False)),
                ('auto_review_on_mr', models.BooleanField(default=True)),
                ('exclude_file_types', models.TextField(blank=True, default='[]')),
                ('ignore_file_patterns', models.TextField(blank=True, default='[]')),
                ('gitlab_data', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('project_id', models.IntegerField(db_index=True)),
                ('project_name', models.CharField(max_length=255)),
                ('merge_request_iid', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('payload', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['event_type', 'created_at'], name='webhook_log_event_t_4ba948_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['project_id', 'merge_request_iid'], name='webhook_log_project_485005_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='projects_project_e2329d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['review_enabled', 'created_at'], name='projects_review__3d1786_idx'),
        ),
        migrations.AddIndex(
            model_name='mergerequestreview',
            index=models.Index(fields=['status', 'created_at'], name='merge_reque_status_2f7b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='mergerequestreview',
            index=models.Index(fields=['project_id', 'merge_request_iid'], name='merge_reque_project_0a69e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mergerequestreview',
            unique_together={('project_id', 'merge_request_iid')},
        ),
    ]
