# Generated by Django 4.1.13 on 2025-11-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='request_body_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='request_headers',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['request_id'], name='webhook_log_request_883d27_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['remote_addr'], name='webhook_log_remote__b709ca_idx'),
        ),
    ]
