# Generated by Django 4.1.13 on 2025-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_webhooklog_remote_addr_webhooklog_request_body_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequestreview',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mergerequestreview',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mergerequestreview',
            name='llm_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mergerequestreview',
            name='notification_result',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='mergerequestreview',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mergerequestreview',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='mergerequestreview',
            index=models.Index(fields=['request_id'], name='merge_reque_request_200ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='mergerequestreview',
            index=models.Index(fields=['is_mock', 'created_at'], name='merge_reque_is_mock_1d77de_idx'),
        ),
    ]
