# Generated by Django 4.1.13 on 2025-11-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_mergerequestreview_is_mock_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mergerequestreview',
            unique_together=set(),
        ),
    ]
