# Generated by Django 4.1.13 on 2025-11-06 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_default_project_notification_settings(apps, schema_editor):
    Project = apps.get_model('webhook', 'Project')
    ProjectNotificationSetting = apps.get_model('webhook', 'ProjectNotificationSetting')
    NotificationChannel = apps.get_model('llm', 'NotificationChannel')

    default_channels = NotificationChannel.objects.filter(is_active=True)

    gitlab_channel = default_channels.filter(notification_type='gitlab').order_by('-updated_at').first()
    gitlab_enabled = True
    if gitlab_channel is not None:
        gitlab_enabled = gitlab_channel.is_default and gitlab_channel.is_active

    non_gitlab_channels = default_channels.filter(is_default=True).exclude(notification_type='gitlab')

    for project in Project.objects.all():
        if project.gitlab_comment_notifications_enabled != gitlab_enabled:
            project.gitlab_comment_notifications_enabled = gitlab_enabled
            project.save(update_fields=['gitlab_comment_notifications_enabled'])

        for channel in non_gitlab_channels:
            ProjectNotificationSetting.objects.get_or_create(
                project=project,
                channel=channel,
                defaults={'enabled': True},
            )


def remove_default_project_notification_settings(apps, schema_editor):
    ProjectNotificationSetting = apps.get_model('webhook', 'ProjectNotificationSetting')
    ProjectNotificationSetting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_notificationchannel_and_more'),
        ('webhook', '0004_alter_mergerequestreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlab_comment_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProjectNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_settings', to='llm.notificationchannel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='webhook.project')),
            ],
            options={
                'db_table': 'project_notification_settings',
                'ordering': ['project'],
                'unique_together': {('project', 'channel')},
            },
        ),
        migrations.RunPython(
            create_default_project_notification_settings,
            reverse_code=remove_default_project_notification_settings,
        ),
    ]
