# Generated by Django 4.1.13 on 2025-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_project_gitlab_comment_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enabled_webhook_events',
            field=models.TextField(blank=True, default='[]', help_text='启用的webhook事件规则ID列表'),
        ),
    ]
