# Generated by Django 4.1.13 on 2025-11-10 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_webhookeventrule_and_more'),
        ('webhook', '0006_project_enabled_webhook_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWebhookEventPrompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_prompt', models.TextField(blank=True, default='', help_text='自定义的代码审查提示词，支持占位符变量，留空则使用系统默认 Prompt')),
                ('use_custom', models.BooleanField(default=False, help_text='是否使用自定义 Prompt，false 则使用系统默认')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_rule', models.ForeignKey(help_text='关联的 Webhook 事件规则', on_delete=django.db.models.deletion.CASCADE, related_name='project_prompts', to='llm.webhookeventrule')),
                ('project', models.ForeignKey(help_text='关联的项目', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_event_prompts', to='webhook.project')),
            ],
            options={
                'db_table': 'project_webhook_event_prompts',
                'ordering': ['project', 'event_rule'],
            },
        ),
        migrations.AddIndex(
            model_name='projectwebhookeventprompt',
            index=models.Index(fields=['project', 'event_rule'], name='project_web_project_592241_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwebhookeventprompt',
            index=models.Index(fields=['use_custom'], name='project_web_use_cus_ad2ad8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectwebhookeventprompt',
            unique_together={('project', 'event_rule')},
        ),
    ]
