# Generated by Django 4.1.13 on 2025-11-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_projectwebhookeventprompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='log_level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', help_text='日志级别', max_length=10),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='skip_reason',
            field=models.TextField(blank=True, help_text='跳过处理的原因(WARNING级别)', null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='error_message',
            field=models.TextField(blank=True, help_text='错误消息(ERROR级别)', null=True),
        ),
    ]
